### ISSUE TITLE
Model errors internationalization with I18n yml files

### ISSUE THREAD

**Issue by adriacarro** [globalize/globalize#657]
Is there a way to internationalize Globalize attributes errors like attributes without Globalize?

I.e. product model with name and description and only name is globalized for :en and :es locales.

**app/models/product.rb**
```ruby
class Product < ApplicationRecord

  ## Translations

  translates :name, touch: true
  globalize_accessors locales: %i[en es], attributes: %i[name]


  ## Validations

  validates_associated :translations
  translation_class.validates :name, presence: true
  validates :description, presence: true


end

```

**app/config/locales/en.yml**
```yml
en:
  activerecord:
    errors:
      models:
        product:
          attributes:
            name:
              blank: "can't be blank"
            description:
              taken: "can't be blank"
```

If I leave name attribute blank, error message I've defined will not show. Which is the correct way to do this?

Thanks!
